services:
  postgres:
    image: postgres:16-alpine
    container_name: pep_vendas_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pep
      POSTGRES_PASSWORD: pep123
      POSTGRES_DB: pep_vendas
    volumes:
      - pep_vendas_pgdata:/var/lib/postgresql/data

volumes:
  pep_vendas_pgdata:
